### PR TITLE
Support for switching target environments

### PR DESCRIPTION
**Pull request by nonnonstop**
# Description

Add the ability to switch behavior depending on the target environment (i.e., online version, local version, a1111 extended version).

* Moves environment-dependent functions and variables to `src/environments`. For example, `src/environments/online/` for the online version, `src/environments/local/` for the local version, and `src/environments/extension` for the a1111 extension version.
* Use the alias config in vite.config.ts to select which directory in `src/environments` will be imported depending on the target environment.

# File changed

* `src/body.ts`
  * Allow local and extention versions to retrieve assets from different URLs.
* `src/config.ts`
  * Move the function of background image.
* `src/editor.ts`
  * Move the functions of generated/background image.
  * Add callback after image generation to move tab in the extention version.
  * Allow to hide Stats.
* `src/main.tsx`
  * Move init code and css.
  * Move the location of dat.gui creation to change the gui location in the extention version.
  * Change to not override the Width and Height settings if these have already been set in init.
  * Export the `editor` variable for external use in the extention version.
* `src/util.ts`
  * Move the function of background image.
* `vite.config.ts`
  * Add `resolve.alias` config.

### CODE REVIEW

**Comment by ZhUyU1997** [comment]
Greate Work

**Comment by ZhUyU1997** [comment]
I don't think environment aliases are necessary as they are very different and not generic. Better to use an interface to replace it

**Comment by nonnonstop** [comment]
:+1: :+1: :+1: 
Thank you for your support.

**Comment by nonnonstop** [comment]
@ZhUyU1997 This directory structure is no longer required since we changed to use iframe. If you don't like it, you can revert to the previous structure.

**Pull request merged**
